apiVersion: v1
kind : Service
metadata:
  name: grafana-service
  labels:
     app: grafana

spec:
  selector:
     app: grafana
  type : NodePort
  ports:
    - name : http
      protocol : TCP
      targetPort: 3000
      port : 3000
