apiVersion : v1
kind : Deployment
metadata :
  namespace : monitoring
  annotations :
  creationTimeStamp: null
  generation: 1
  labels:
    app: influxdb
  name : influxdb
  spec:
    replicas: 1
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
    selector:
      matchLables:
        app: influxdb
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimeStamp: null
        labels:
          app : influxdb
      spec:
        containers:
          - envFrom:
            - secretRef:
                name : influxdb-cred
            image : docker.io/influxdb:1.6.4
            imagePullPolicy : IfNotPresent
            name : influxdb
            resources : {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/influxdb
              name: var-lib-influxdb
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: var-lib-influxdb
            persistentVolumeClaim:
              claimName: influxdb-pvc

