---
apiVersion: v1
kind: Service
metadata:
  name : nodejs-nodeport
  labels:
    app: nodejs-sample

spec:
  selector:
    app: nodejs-sample
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      targetPort: 3000
      port: 3000
