---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-sample
  name: nodejs-nodeport
spec:
  ports:
    -
      name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: nodejs-sample
  type: NodePort


