---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-sample
  name: nodejs-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: "rbj1456/k8images:nodejs-sample-v1"
      ports:
        - name : http
          protocol: TCP
          containerPort: 3000