---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-sample
  name: nodejs-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      labels:
        app: nodejs-sample
    spec:
      containers:
        -
          image: "rbj1456/k8images:nodejs-sample-v1"
          name: nodejs-sample
          ports:
            -
              containerPort: 3000
              name : HTTP
